database_url_01: postgresql://postgres:postgres@localhost:5434/PRO_CG?sslmode=require
 
 -------------- celery@DESKTOP-KNMVS5V v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35 2025-03-26 22:10:52
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         config:0x7f074da341d0
- ** ---------- .> transport:   redis://172.17.234.65:6380//
- ** ---------- .> results:     postgresql://postgres:**@localhost:5434/PRO_CG
- *** --- * --- .> concurrency: 12 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . executors.bash.execute
  . executors.python.execute
  . executors.stored_function.execute
  . executors.stored_procedure.execute

[2025-03-26 22:10:53,379: WARNING/MainProcess] /d01/def/app/server/flask/flask_venv/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-03-26 22:10:53,425: INFO/MainProcess] Connected to redis://172.17.234.65:6380//
[2025-03-26 22:10:53,425: WARNING/MainProcess] /d01/def/app/server/flask/flask_venv/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-03-26 22:10:53,428: INFO/MainProcess] mingle: searching for neighbors
[2025-03-26 22:10:54,435: INFO/MainProcess] mingle: all alone
[2025-03-26 22:10:54,453: INFO/MainProcess] celery@DESKTOP-KNMVS5V ready.
[2025-03-26 22:17:03,139: INFO/MainProcess] Task executors.stored_function.execute[1698a901-ce6d-4a37-977c-6fcc827be883] received
[2025-03-26 22:17:03,143: INFO/ForkPoolWorker-8] Attempting to connect to the database for function
[2025-03-26 22:17:05,239: INFO/ForkPoolWorker-8] Database connection for function successful.
[2025-03-26 22:17:06,098: INFO/ForkPoolWorker-8] Stored function output: {'message': 'Hello World'}
[2025-03-26 22:17:14,734: INFO/ForkPoolWorker-8] Task executors.stored_function.execute[1698a901-ce6d-4a37-977c-6fcc827be883] succeeded in 11.591892291000022s: {'user_task_name': 'Hello World (Stored Function)', 'task_name': 'func_hello_world', 'executor': 'executors.stored_function.execute', 'user_schedule_name': 'Immediate', 'redbeat_schedule_name': 'Immediate_87629bf8-db20-43bf-8c9f-84505a08b1a4', 'schedule': {}, 'args': ('hello_world', 'Hello World (Stored Function)', 'func_hello_world', 'Immediate', 'Immediate_87629bf8-db20-43bf-8c9f-84505a08b1a4', {}), 'kwargs': {}, 'parameters': {}, 'result': {'message': 'Hello World'}, 'message': 'Stored function executed successfully!'}
